homeSuccess:
  customize:
    timelineCommunity:
      template: [timeline, communityTimelineBy5]
      parts: [communityHome]
      target: [after]
      is_component: true

smtHomeSuccess:
  customize:
    smtTimelineCommunity:
      template: [timeline, smtTimelineCommunity] 
      parts: [smtCommunityHomeTop]
      target: [after]
      is_component: true
