timelineAll:
  caption:
    ja_JP: "SNSメンバーのタイムライン"
  description:
    ja_JP: "SNSメンバー全員のタイムラインが表示されます。"
  component: [timeline, timelineAll]

timelineMentions:
  caption:
    ja_JP: "自分宛のタイムライン"
  description:
    ja_JP: "自分宛のタイムラインが表示されます。"
  component: [timeline, timelineMentions]
