timelineScreenName:
  _attributes:
    caption: "スクリーンネーム設定"
    enable_pc: true
    eneble_mobile : false
  op_screen_name:
    Name:       "op_screen_name"
    Caption:    "スクリーンネーム"
    FormType:   "input"
    ValueType:  "op_screen_name"
    IsRegist:   true
    IsConfig:   true
    IsUnique:   true
    IsRequired: true
    IsConfirm:  false

