indexSuccess:
  javascripts: ["http://code.jquery.com/jquery-latest.min.js", "http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.js", "/opTimelinePlugin/js/jquery.timeline.js", "/opTimelinePlugin/js/gorgon.js"]
  stylesheets: ["/opTimelinePlugin/css/custom-theme/jquery-ui-1.8.16.custom.css", "/opTimelinePlugin/css/prettyPopin.css", "/opTimelinePlugin/css/gorgon.css"]

smtIndexSuccess:
  javascripts: ["http://code.jquery.com/jquery-latest.min.js", "http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.js", "/opTimelinePlugin/js/jquery.timeline.js", "/opTimelinePlugin/js/gorgon.js"]
  stylesheets: ["http://houou.github.com/bootstrap.css", "http://houou.github.com/main.css", "/opTimelinePlugin/css/custom-theme/jquery-ui-1.8.16.custom.css", "/opTimelinePlugin/css/prettyPopin.css", "/opTimelinePlugin/css/gorgon.css"]

memberSuccess:
  javascripts: ["http://code.jquery.com/jquery-latest.min.js", "http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.js", "/opTimelinePlugin/js/jquery.timeline.js"]
  stylesheets: ["/opTimelinePlugin/css/custom-theme/jquery-ui-1.8.16.custom.css", "/opTimelinePlugin/css/prettyPopin.css", "/opTimelinePlugin/css/gorgon.css"]

mentionsSuccess:
  javascripts: ["http://code.jquery.com/jquery-latest.min.js", "http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.js", "/opTimelinePlugin/js/jquery.timeline.js", "/opTimelinePlugin/js/timeline.mentions.js"]
  stylesheets: ["/opTimelinePlugin/css/custom-theme/jquery-ui-1.8.16.custom.css", "/opTimelinePlugin/css/prettyPopin.css", "/opTimelinePlugin/css/custom-theme/timeline.css"]
listSuccess:
  has_layout: false
  http_metas:
    content-type: application/x-javascript+json
listMentionSuccess:
  has_layout: false
  http_metas:
    content-type: application/x-javascript+json
jsSuccess:
  has_layout: false
  http_metas:
    content-type: application/x-javascript
timelinePluginSuccess:
  has_layout: false
  http_metas:
    content-type: application/x-javascript

