all:
  javascripts: ["/opTimelinePlugin/js/jquery-1.6.2.min.js", "http://ajax.microsoft.com/ajax/jquery.templates/beta1/jquery.tmpl.js", "/opTimelinePlugin/js/jquery-ui-1.8.16.custom.min.js"]
  stylesheets: ["/opTimelinePlugin/css/custom-theme/jquery-ui-1.8.16.custom.css", "/opTimelinePlugin/css/custom-theme/timeline.css"]


